name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Установить Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установить зависимости
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pytesseract pdf2image opencv-python

    - name: Собрать EXE
      run: |
        pyinstaller --onefile --noconsole ttn_to_xml_gui.py

    - name: Сохранить артефакт
      uses: actions/upload-artifact@v3
      with:
        name: ttn_to_xml_gui
        path: dist/ttn_to_xml_gui.exe
